name: versevision_camera
description: Mobile camera app for VerseVision
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.3
  http: ^1.6.0
  mobile_scanner: ^7.1.4
  flutter_webrtc: ^1.2.1
  shared_preferences: ^2.5.4
  battery_plus: ^7.0.0
  wakelock_plus: ^1.4.0
  google_fonts: ^7.1.0
  path_provider: ^2.1.5
  record: ^6.1.2
  permission_handler: ^11.3.1
  share_plus: ^7.2.0
  url_launcher: ^6.3.2
  speech_to_text: ^7.3.0

dependency_overrides:
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bible_kjv.json
    - assets/bibles/
